yabwe/medium-editor

- spec/helpers/util.js
- spec/selection.spec.js
- src/js/medium-editor.js
This pull request allows for a config option that will make button states update even when the selection is collapsed.
Use case: imagine that you want to know what toolbar should be active in the range that the cursor is in, even when the cursor has no selection.
> allow toolbar button states to change when selection is collapsed

- spec/toolbar.spec.js
- src/js/medium-editor.js
Use case: as a developer, I want to add some custom behavior that will fire on my MediumEditor instance when the toolbar is hidden.
This changeset also adds a little bit of code that will clear any existing `setTimeout` function that exists when `blurFunction` is re-called.
> Add optional 'onhidetoolbar' method

- spec/anchor-preview.spec.js
- spec/init.spec.js
- src/js/medium-editor.js
found a case where different medium-editor instances could be assigned the same ID if the first instance was deactivated, then activated (it would get re-assigned to an already-assigned ID).
this changeset also fixes a few cases where an ID was being assigned to a smaller piece of medium-editor (e.g. `#medium-editor-toolbar-actions` without a unique identifier being appended to the end of that smaller piece)
> Ensure medium ID's uniqueness

- src/js/medium-editor.js
This will be a performance improvement.  It will avoid calling into `getSelectionStart` until we know we actually need the selection (if the user hits spacebar, we need to know if their in an anchor or not)
> Avoid grabbing selection on keypress when it's not being used

- spec/init.spec.js
- spec/toolbar.spec.js
- src/js/medium-editor.js
When 'disableAnchorForm' is passed as an option:
- Don't create the anchor form element
- Don't attach event handlers to the document, window, and/or anchor form which are used soley for handling user interaction with the anchorForm
> Support disabling anchorForm

- spec/init.spec.js
- spec/placeholder.spec.js
- src/js/medium-editor.js
When `disablePlaceholders` is passed as an option to medium-editor:
- Do not add/remove the 'medium-editor-placeholder' class on the contenteditable element
- Don't attach event handlers which had the sole purpose of handling when a placeholder should be shown/hidden
> Support disabling placeholders

- src/js/medium-editor.js
The `MediumEditor.on` helper function conveniently tracks all our event handlers, so that we may cleanup / detach them when needed.  
There are a few spots in the code where this.on was not being used, so this updates those places accordingly
> Use this.on() for attaching all event handlers

- src/js/medium-editor.js
When the link editor is open, let the user hit ESC to close it and return to the main toolbar (just like the X button)
> Handle ESC key in link editor

- src/js/medium-editor.js
There is a delay when hiding the toolbar, so that if you have multiple instances of medium-editor on the page, you can cause multiple toolbars to appear at the same time.  This delay is NOT controlled by the `delay` option, it is hard coded and doesn't appear to be necessary, at least as far as I can tell.
The goal of these changes is to make sure we're using the `delay` option properly, and try to remove places where a hard-coded delay is actually creating a UI lag. 
+ The 'delay' option indicates that it should be used for the amount of time to delay the toolbar or anchorPreview from being displayed.  So, ensure this value is only being used in places where we would show the toolbar or anchor preview
+ For places in the code where we just want to debounce (prevent a method from being …
> Standardize usage of setTimeout for UX delays vs debouncing vs deferring

- spec/toolbar.spec.js
- src/js/medium-editor.js
**This fixes 2 specific issues:**
1) When creating more than one instance of medium-editor on a page, when switching between focus on the two editors the toolbar for one will not be hidden when the toolbar for the other is shown.  (This was caused by attaching the `debounce()`'d methods to medium-editor prototype, which essentially made them singleton across all instances)
2) In some cases, doing a `debounce` for handling blur can actually prevent the toolbar from an instance from ever being hidden.  This was fixed by using throttle instead.
**Changes**
- Use a '[throttle](http://underscorejs.org/docs/underscore.html#section-70)' style for methods we don't want to run too often instead of '[debounce](http://underscorejs.org/docs/underscore.html#section-71)'
- Attach the `throttle()`'d …
> Throttle instead of debounce + don't attach to prototype

- src/js/medium-editor.js
This allows us to use some parts of medium-editor when we create custom buttons for the toolbar
> Pass medium instance to calls to extension.getButton()

- spec/events.spec.js
- src/js/medium-editor.js
Currently `off()` doesn't remove any event listeners or remove the entry from `this.events` (memory leak). This is because of the `indexOf` check (which checks strict equality, not deep equality).
```js
[[1,2,3]].indexOf([1,2,3]) === -1
```
> Bugfix: off() doesn't remove any event listeners

- spec/toolbar.spec.js
- src/js/medium-editor.js
+ Calling `MediumEditor.stopSelectionUpdates()` will prevent the logic in `checkSelection()` from running
+ Calling `MediumEditor.startSelectionUpdates()` will undo the action done by `stopSelectionUpdates()` and allow the logic in `checkSelection()` to behave normally.
> Support enabling/disabling checkSelection updates externally

- README.md
- spec/init.spec.js
- src/js/medium-editor.js
This is a proposed fix for Issue #371 
In firefox, there are cases (ie doubleclick of a word) where the selectionRange start will be at the very end of an element.  In other browsers, the selectionRange start would instead be at the very beginning of an element that actually has content.
example:
```
<div contenteditable="true">
<span>foo</span><span>bar</span>
</div>
````
If the text `bar` is selected, most browsers will have the selectionRange start at the beginning of the `bar` span.  However, there are cases where firefox will have the selectionRange start at the end of the `foo` span.  The contenteditable behavior will be ok, but if there are any properties on the `bar` span, they won't be reflected accurately in the toolbar (ie 'Bold' button wouldn't be active)
So, for cases where …
> Standardize where in the DOM a range begins

- spec/activate.spec.js
- spec/delay.spec.js
- src/js/medium-editor.js
Currently, calling `deactivate()` when there's something waiting to be called because of `setTimeout()` or `throttle()` can lead to exceptions, because most methods assume the editor is active at the time of calling. This can lead to errors like:
```
Uncaught TypeError: Cannot read property 'classList' of undefined
MediumEditor.showAnchorPreview (anonymous function)
```
This PR makes all async delay/throttle logic check `isActive` before calling the function.
> Bugfix: ignore delayed/throttled functions when editor disabled

- src/js/medium-editor.js
There are currently some direct references to `window` and `document` throughout the code.  These should be using the `ownerDocument` and `contentWindow` values passed in via options, as the rest of the code is using.
> Use correct references to 'document' and 'window'

- spec/init.spec.js
- src/js/medium-editor.js
This will remove code paths that were always running twice, which included redundantly attaching event handlers.  This also improves some code and gets ride of some duplication around elements and placeholders.
+ Ensure `this.elements` is always initialized to an array (never a node, NodeList, or null)
+ Remove unneeded call to `this.updateElementList()`
+ Remove unneeded `bindKeyPress` function (`setPlaceholders()` does the same thing and is always called during initalization)
+ Ensure all placeholder code is using the same `activatePlaceholder()` and `placeholderWrapper()` function
+ Begin using `Array.prototype.forEach` and `Function.prototype.bind` 
+ [Array.prototype.forEach](http://kangax.github.io/compat-table/es5/#Array.prototype.forEach) and …
> Improve placeholders and elements

- dist/css/medium-editor.css
- src/sass/medium-editor.scss
If you have newlines in your placeholder attribute like so:
The newlines aren't respected:
This change now has the placeholder display newlines:
> Newlines were not being respected on content placeholders

- package.json
@daviferreira –  what do you think of this? feel free to reject, just wondering.
by default, npm modules are published-to and fetched-from
the `http://registry.npmjs.com` registry.
however, it is possible to have different registries set up for NPM on a
system or per-repository/per-directory basis.
For example, some people have a system-level npm config that points their registry to `http://registry.npmjs.eu`. This is good for fetching packages if you're a developer in EU, but bad for publishing, because you cannot publish to the european mirror (it is read only). You can read an article about that here: http://shapeshed.com/using-the-european-npm-mirror/
this commit ensures that developers are publishing to the canonical
registry for this project (`http://registry.npmjs.org`).
> specify npm registry in package.json

- spec/activate.spec.js
- spec/anchor-preview.spec.js
- spec/anchor.spec.js
- spec/buttons.spec.js
- spec/helpers/util.js
- spec/resize.spec.js
- spec/selection.spec.js
- spec/toolbar.spec.js
- src/js/medium-editor.js
+ Create a test helper method `selectElementContentsAndFire()` for selecting elements and triggering medium-editor to update based on that selection
+ Fix a bug in `getSelectedParentElement()` where a text-node could returned, which is not a parent of any elements.  This was causing certain buttons to show the 'opposite' of whether they should be active or not based on the selection
+ Fix all tests that were broken when running in chrome
+ General test cleanup and consolidation
> Fix bug in getSelectedParentElement + tests in browsers

- spec/anchor.spec.js
- spec/buttons.spec.js
- spec/cleanup-paste.spec.js
- spec/events.spec.js
- spec/exploits.spec.js
- spec/placeholder.spec.js
- src/js/medium-editor.js
+ Fix all the tests that were failing when running in firefox
+ Thanks to @nchase , also fixed all the tests that were still failing in IE
+ In cases where firefox or IE are doing something very differently from other browsers, branch the test cases to keep the intent of the case without having to remove them completely
> Fix Browser Tests in Non-Webkit-based Browsers

- spec/anchor-preview.spec.js
- src/js/medium-editor.js
We're currently using ME on a platform that uses links similar to the following format... 
```html
http://{custom_domain}.com/
```
However the current anchor preview and anchor form fetch the link address by using the `href` property directly on the anchor element, the browser returns the encoded link, something like ....
```html
http://%7Bcustom_domain%7D.com/
``` 
By fetching from the attributes property instead it will return the unencoded link.
> Fix showing and writing encoded links 

- src/js/medium-editor.js
Changed the numeric constants to named "constants" to improve readability of the code, issue: #398 
Only included key codes that are in use and started to remove comments that got redundant by this change.
> Changed from number constants to named constants when checking key codes

- README.md
As requested [here](https://github.com/daviferreira/medium-editor/issues/26#issuecomment-73412568) by @daviferreira, I added the markdown extension I developed for Medium Editor.
So, enjoy using it! :smile:
> Added Markdown Editor Markdown extension.

- README.md
This is useful when we need to insert custom HTML (e.g. `<hr>`s). :smile: We needed such an extension at @jillix.
> Added custom HTML extension.

- dist/js/medium-editor.js
https://github.com/daviferreira/medium-editor/issues/412
fix chaining on 'bindDragDrop' function when 'imageDragging' is set to 'false'.
> fix 'imageDragging: false' option.

- spec/buttons.spec.js
- src/js/medium-editor.js
`text-decoration` is not inherited by default, so we can't use it reliably to determine if text is underlined or strikethrough in the toolbar :disappointed:
> Don't use styles for detecting underline + strikethrough

- src/js/medium-editor.js
+ Expose `ButtonsData` so we can make buttons that have the same content or behavior of existing buttons
+ Expose `DefaultButton` so we can make extensions that re-use existing functionality of built-in buttons
+ Break up work in DefaultButton constructor so it can be overridden easier
> Expose button data for use for other extensions

- src/js/paste.js
When creating RegExp, if you use the `g` param the RegExp will maintain state as long as the variable exists in scope.  This means that the RegExp will behave differently each time its used after the first, depend on the original string that was used.
To avoid any issues with this, we should create the paste RegExp objects each time the paste runs (instead of declaring them one time and reusing them).
> RegExp with 'g' param maintain state - don't declare globally

- spec/resize.spec.js
- spec/toolbar.spec.js
I've attempted to fix the unit-tests that are ignored. All tests seem to pass &ndash; although `expect(editor.elements.length).toEqual(3);` was initially set to `2` but in having a look at the unit-test below, that also has `toEqual(3)` despite disabling the toolbar. I assume the codebase changed, and as this test was ignored, wasn't kept up-to-date.
Please correct me if I'm making a gargantuous incorrect assumption :beers: &ndash; which is quite possible.
There is [another ignored test](https://github.com/Wildhoney/medium-editor/blob/master/spec/activate.spec.js#L91) but I am unsure as to why this is ignored. I didn't want to bring it back without knowing the reason why. Although this also passes.
> Attempt to fix ignored unit-tests

- spec/content.spec.js
This should fix #520 @daviferreira can you verify?
Yet again, firefox can throw errors in certain situations when a programmatically modified selection is followed by a call to `document.execCommand()`.
Changing a test to trigger a button click in the toolbar instead of manually calling `insertorderedlist` seems to keep firefox happy in this case.
> Workaround firefox test failure

- spec/exploits.spec.js
- spec/paste.spec.js
- src/js/paste.js
in a `<p></p>`. In FF, when pasting this text in a parapgraph, it would
result in 3 paragraphs.
For example:
This is some sample text.	// copy and paste sample right after sample
Expected:
This is some sample sample text.
Actual:
This is some sample
sample
text.
> When pasting text without linefeeds in FF, it was still wrapping text

- demo/index.html
By leaving out the schema, the browser will automatically select between HTTP/HTTPS. This helps with Chrome, who's refusing to load HTTP content, when the main website is served over HTTPS.
> Fix Fontawesome in demo for HTTPS

- README.md
- demo/clean-paste.html
- dist/js/medium-editor.js
- spec/init.spec.js
- spec/paste.spec.js
- src/js/core.js
- src/js/defaults/options.js
- src/js/paste.js
I noticed after migrating from v3.0.9 to v4.x the option name `cleanPastedHTML` has been deprecated and should be used `paste.cleanPastedHtml` instead. it turns out that this deprecated option is not displaying warning in the console and also when passing the newly option `paste.cleanPastedHtml` the content does not get cleaned as expected.
This PR addresses to:
- fix missing deprecated warning for passing the option `cleanPastedHTML` used in v3.0.9 and earlier.
- fix `cleanPastedHtml` option. As of v4.0.0 this option is defined in camelCase format when this options is passed along with `paste` option it does not clean up the pasted html.
> fix BC break warn for cleanPastedHTML option

- README.md
The README incorrectly suggests that the `input` event can be used to listen to contenteditable changes in IE9+, when in fact it does not work in any released version of IE up through IE 11.
> Update `input` documentation in README.md

- spec/toolbar.spec.js
- src/js/core.js
- src/js/events.js
- src/js/extension.js
- src/js/toolbar.js
Add custom eventos for showing and hiding the toolbar so extensions can listen to it if they want instead of using a predefined method.
> Toolbar events

- spec/content.spec.js
- spec/helpers/util.js
- src/js/core.js
On recent Safari browsers, it's impossible to insert a line break as Shift + Enter just makes a new paragraph.
Ctrl + Enter works better, creating the `<br>`, but it also creates a new paragraph and results in a paragraph inside another.
In addition to checking !event.shiftKey in handleKeyup(), the code should check for !event.ctrlKey so that execCommand('formatBlock', false, 'p') won't be called.
> Fix line breaks on Safari

- spec/extension.spec.js
- src/js/core.js
- src/js/extension.js
- src/js/extensions/auto-link.js
- src/js/extensions/button.js
- src/js/extensions/fontsize.js
- src/js/extensions/image-dragging.js
- src/js/util.js
This PR covers passing `options.ownerDocument` and `options.contentWindow` into each extension as `.document` and `.window` properties (respectively)
> Pass document + window properties to each extension

- spec/init.spec.js
- src/js/core.js
This fixes issue called out in issue #634 
The elements array is emptied after calling `destroy()`, however this means that calls to `setup()` afterwards will not have any elements and thus the editor will be useless.
The fix is to store the selector passed in during initialization, and re-use this same list each time `setup()` is called.
> Fix issue where elements array is lost after destroy

- spec/extension.spec.js
- src/js/core.js
- src/js/extension.js
- src/js/extensions/anchor-preview.js
- src/js/extensions/anchor.js
- src/js/extensions/auto-link.js
- src/js/extensions/button.js
- src/js/extensions/fontsize.js
- src/js/extensions/image-dragging.js
- src/js/extensions/paste.js
- src/js/extensions/placeholder.js
This PR adds some helper methods to all extensions, including accessors into MediumEditor methods + properties.  There are also some minor changes to cleanup tests and remove unneeded defaults from extensions.
* `.on()` + `.off()` -> helpers that call directly into `MediumEditor.on()` + `MediumEditor.off()`
* `.subscribe()` -> calls directly into `MediumEditor.subscribe()`
* `.execAction()` -> calls directly into `MediumEditor.execAction()`
* `.getEditorElements()` + `.getEditorId()` -> accessors for MediumEditor's array of elements and unique id (respectively)
* `.getEditorOption()` -> accessor for specific MediumEditor options
> Create extension helper methods

- CONTRIBUTING.md
- README.md
Like I said on Gitter, I would like to update CONTRIBUTING to specify that user who forks and then create a PR **shouldn't** commit the _dist_ directory.
This will ease all merge requests and then we just need to build these files on our own when we need to cut a new release.
I don't know if the message is clear enough in the README / CONTRIBUTING. What do you think?
> Ask users to not commit dist files

- spec/anchor-preview.spec.js
- spec/auto-link.spec.js
- spec/extension.spec.js
- spec/fontsize.spec.js
- spec/placeholder.spec.js
- src/js/core.js
- src/js/events.js
- src/js/extension.js
- src/js/extensions/anchor-preview.js
- src/js/extensions/anchor.js
- src/js/extensions/auto-link.js
- src/js/extensions/fontsize.js
- src/js/extensions/placeholder.js
- src/js/toolbar.js
This PR deprecates the `deactivate()` method on extension and standardizes on the `destroy()` method.  It also implements `destroy()` for auto-link and placeholder extensions.
> destroy() for extensions

- spec/util.spec.js
- src/js/core.js
- src/js/events.js
- src/js/extensions/anchor.js
- src/js/extensions/auto-link.js
- src/js/extensions/button.js
- src/js/toolbar.js
- src/js/util.js
Instead of always trying to find which key is associated to an event for all browsers, I created a helper in Util to return this key.
I follow what is already done by jQuery.
It'll ease the transition when the `.key` will be compatible with all browsers (https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key)
Are you all ok with the `Util.key(event)` name ? Or should we use `Util.keyCode(event)` ?
> Create Util.key to return key code from an event

- src/js/toolbar.js
* none of the other functions do? or did?
* now that everything is Extension.extend, no named functions are used as ctors
* somehow, someway, the duplicate `var Toolbar; (function(){ Toolbar = function Toolbar(instance){} )();`
is causing uglify2 to output `var x; (function() e = function e(e){})();` which is clearly not right
> remove name of function.

- spec/events.spec.js
- src/js/core.js
- src/js/events.js
Yeah, I don't know why I did this originally, but it's not great to require custom events to be defined before they can trigger.  This fixes that.
> Make custom events not require 'registering' before triggering

- src/js/selection.js
We allow the toolbar to be updated even with a collapsed range when the user enables the `staticToolbar` option along with the `updateOnEmptySelection` option.
Since this is a valid case where we want a range even if the selection is collapsed, `getSelectionRange()` should still return a range in this case.
> Fix updateOnEmptySelection option

- spec/extension.spec.js
- spec/util.spec.js
- src/js/core.js
- src/js/util.js
This PR removes some old methods that we aren't currently using and which would be good to remove since we're prepping v5.0.0 right now.
* `MediumEditor.callExtensions()`
* `MediumEditor.util.getObject()`
* `MediumEditor.util.setObject()`
> Remove Unused Methods

- spec/buttons.spec.js
- src/js/core.js
- src/js/defaults/buttons.js
- src/js/extensions/button.js
Before version 5.0.0, the set of default button configuration was exposed via `MediumEditor.statics.ButtonsData`.  This contained all the config options to differentiate the various built-in MediumEditor buttons (ie `bold`, `italic`, `underline`, etc.)
To give users the ability to access the data, but still align with how our other options and defaults are exposed, I've exposed this set of data via the button prototype (`MediumEditor.extensions.button.prototype.defaults`).
Also, to help reduce the cases where this data might be needed, I've added 2 additional features:
1. The button extension constructor can be invoked and passed the name of a built-in button (instead of an object containing all the button options).  For that case, it will initialize itself with the default config data …
> Expose button default config (replace MediumEditor.statics.ButtonsData)

- README.md
- src/js/core.js
There is now more detailed and thorough documentation in place via the Wiki, which is a superset of the details in the README.  I was thinking it might be better to have a shorter README and provide links to the pages which have documentation. 
Do you all agree or do you think it's better to have a longer, one-stop-shop style README which include detailed documentation and which is maintained via source control?
> Update README to link to Wiki for options + API documentation

- README.md
- demo/auto-link.html
- demo/clean-paste.html
- demo/css/demo.css
- demo/custom-toolbar.html
- demo/index.html
- demo/multi-paragraph.html
- demo/nested-editable.html
- demo/pass-instance.html
- demo/static-toolbar.html
- demo/table-extension.html
- demo/textarea.html
- spec/buttons.spec.js
- spec/init.spec.js
- src/js/core.js
- src/js/defaults/buttons.js
- src/js/defaults/options.js
- src/js/extensions/button.js
- src/js/extensions/toolbar.js
This PR solves two button-related issues in one.
1. The `firstHeader` and `secondHeader` options were not ideal as options on MediumEditor.  They also restricted the amount of header buttons that could be easily configured.
2. Making small tweaks to existing buttons required the creation of a new Extension which would need to extend from `MediumEditor.extensions.button` and would need to know how to use the same set of default options that the built-in button would use.
Changes in this PR:
* Add built-in button support for all header types (`h1`, `h2`, `h3`, `h4`, `h5`, and `h6`)
* Remove support for the `firstHeader` and `secondHeader` options.
* Allow for overriding built-in button options by accepting both strings and objects into the `options.toolbar.buttons` array passed in during …
> Custom Button Options + Deprecate Header Options

- README.md
- spec/anchor.spec.js
- spec/keyboard-commands.spec.js
- src/js/extensions/anchor.js
- src/js/extensions/keyboard-commands.js
- src/js/util.js
We handle shortcut by listening to onKeyDown. There is also onKeyPress but it is only fired when something is inserted in the content. For example, when you hit the shift key, keyPress is never fired because it does not insert something in the content.
onKeyPress & onKeyDown doesn't handle the key code in the same way.
When you hit `b` letter, onKeyDown will receive 66 but onKeyPress will receive 98.
When you hit `B` letter, onKeyDown will receive 66 and onKeyPress will receive 66.
The way we transcript `b` shortcut to a number is by using: `'b'.charCodeAt(0)` which is 98
As you might guess, it can't work. Because we will receive 66 when we are waiting for 98 to bold the content;
Using uppercase letter fix the problem because `'B'.charCodeAt(0)` is equal to 66.
You can test that: …
> Use uppercase version of shortcut

- spec/selection.spec.js
- src/js/core.js
- src/js/util.js
In Gecko, importing the selection when the cursor was in an empty
paragraph such as `<p><br /></p>` or `<p><img /></p>` would set the BR
or IMG to be the start and end container of the selected range. The
cursor would get 'stuck' and nothing happened when the user typed.
An example demonstrating this issue in Gecko is here:
http://jsbin.com/kaduwanego/edit?html,js,output
> Auto-link: never import selection to focus on a BR or IMG

- spec/selection.spec.js
- src/js/selection.js
- src/js/util.js
Some of the auto-link code I modified assumed that blocks can't be inside blocks.  Apparently, in firefox, all `<blockquote>` elements have a `<p>` inside of them, so I was very wrong.
I've also added a helper function for checking whether an element is one of the things we consider a "block" element, and used this helper everywhere we were referencing `Util.parentElements`
> Fix issue with block-containers assumptions for selection

- spec/auto-link.spec.js
- spec/content.spec.js
- spec/fontsize.spec.js
- spec/header-tags.spec.js
- spec/selection.spec.js
- spec/textarea.spec.js
- spec/util.spec.js
- src/js/core.js
- src/js/extensions/button.js
- src/js/extensions/fontsize.js
- src/js/extensions/paste.js
- src/js/extensions/toolbar.js
- src/js/selection.js
- src/js/util.js
I propose we begin to use `nodeName` everywhere instead of `tagName`.  `nodeName` is defined on the `Node` class for all nodes, whereas `tagName` only exists on `Element`.  Thus, we can always use `nodeName` safely, whereas `tagName` might not exists.  This simplifies the code, avoids unnecessary exceptions, and since `nodeName` and `tagName` are identical on `Element`s, the behavior of our code should remain the same.
I've also fixed a line of code in toolbar that was broken and always returning true. I've also ensured that when we move up the DOM hierarchy while checking the state of elements, we're not bailing out early if we start at a text node (which I don't believe could have happened anyway).
Lastly, I've reused the new `Util.isMediumEditorElement()` helper everywhere in the code …
> Use nodeName instead of tagName + Fix busted code in toolbar

- spec/util.spec.js
- src/js/core.js
- src/js/selection.js
- src/js/util.js
This proposes some lingering cleanup to some Utility methods:
In `Util`:
* Rename `getBlockContainer()` to `getTopBlockContainer()`
* Also add a fix to ensure the method does what it's supposed to
* Remove `now()` function
* Rename `.parentElements` to `.blockContainerElementNames`
* Expose `.emptyElementNames`
* Reuse `traverseUp()` in `getFirstSelectableLeafNode()`
In `Selection`:
* Remove uneeded `getSelectionData()`
* `Util.getTopBlockContainer()` can replace what the previous function was doing
> Util cleanup

- src/js/extensions/anchor-preview.js
This PR allows the `.positionPreview()` method of the anchor-preview extension to take in an argument which represents the anchor to position the preview relative to.  If the argument is not passed, it defaults to the use of the `this.activeAnchor` member variable.
This makes the method more re-usable for custom extensions that are extending `anchorPreview`.
> Make anchorPreview.positionPreview more reusable

- spec/anchor.spec.js
- src/js/core.js
- src/js/extensions/auto-link.js
- src/js/extensions/toolbar.js
- src/js/selection.js
- src/js/util.js
When selecting text across inline element boundaries, the built-in
browser createLink command will create 2 or more anchor tags. This is a
weird behavior that the user will find strange when they go to delete or
modify one of the anchor tags and find that their changes don't affect
the other adjacent tags that appear to be part of a single link.
This fixes this problem for selections within a single paragraph or
other parent (block-level) element. If the user has selected text across
multiple parent elements, we fall back to the built-in browser behavior
as there is no way to ensure only a single link is created in this
situation.
> Creating a link should create only one anchor if possible

- src/js/core.js
- src/js/events.js
This PR covers cleaning up some code in the Events object.
1. The Events object maintains setting the `data-medium-focused` attribute on the currently focused editor element. Since Events has a destroy method, Events should be reponsibile for removing this attribute, not the core editor.
2. There were many repeat lines where Event looped through each editor element and attached an event.  I've created a helper method to avoid all of this repeat code.
> Some Events Cleanup

- README.md
- demo/multi-paragraph.html
- spec/init.spec.js
- spec/selection.spec.js
- spec/toolbar.spec.js
- src/js/core.js
- src/js/defaults/options.js
- src/js/extensions/toolbar.js
This PR covers two issues with the `allowMultiParagraphSelection` option.
1. When determining whether the selection spanned multiple block elements, the regular expression used to remove empty elements would remove multiple valid blocks if it found any empty ones: http://stackoverflow.com/questions/3129738/remove-empty-tags-using-regex
2. The `allowMultiParagraphSelection` option should have been moved into the toolbar options for v5.0 but it was missed.  The option has now been moved into the toolbar options, and the `allowMultiParagraphSelection` option on the global options is deprecated and will be removed in v6.0.0
> Fix allowMultiParagraphSelection option

- bower.json
- spec/setup.spec.js
- spec/textarea.spec.js
- src/js/core.js
- src/js/events.js
- src/js/toolbar.js
- Ignore source files (#697)
- Ensure all extra attributes are removed on destroy (#703)
- Ensure div ids are unique when there are multiple textareas (#701)
- Events object should remove data-medium-focused attribute on destroy (#707)
- Fix (badly) broken allowMultiParagraphSelection option (#708)
> Prepare 4.12.6

- src/js/core.js
- src/js/selection.js
This PR breaks up the logic of `MediumEditor.importSelection()` and `MediumEditor.exportSelection()` in such a way that the core functionality of these methods can be exposed generically as helper functions within `Selection`.
This preserves the existing functionality, but allows other utility code to take advantage of this functionality.
> Factor out importSelection + exportSelection into helper methods

- API.md
- CUSTOM-EVENTS.md
- OPTIONS.md
- README.md
- src/js/extensions/README.md
- src/js/extensions/WALKTHROUGH-BUTTON.md
- src/js/extensions/WALKTHROUGH-EXTENSION.md
This PR moves the documentation we have in the Wiki into the source code via markdown files.
This keeps the documentation as close to the code as possible, and allows everyone to search through both documentation and code at the same time to find things that are incorrect or need to be updated.
If we go with this route, I'll change the wiki pages to just link to these documents within the repo.
> Documentation

- spec/anchor-preview.spec.js
- src/js/core.js
We realized in our application that our custom extension was not suppressing the built in anchor preview so we were seeing unstyled, extra and unwanted preview nodes in our application. The unit test should exercise this bug and the couple of lines changes are all that should be needed to fix it, without introducing any breakage for existing users of the built-in.
> Fix for custom extension not suppressing built in anchor preview

- API.md
- README.md
- spec/core-api.spec.js
- spec/events.spec.js
- src/js/core.js
- src/js/events.js
Adds a `setContent` method to set the `innerHTML` of an element at a provided index.
https://github.com/yabwe/medium-editor/issues/405
Return early if `contentCache` not defined in `updateInput`
> Expose setContent method on medium

- spec/anchor-preview.spec.js
- src/js/extensions/anchor-preview.js
- src/js/extensions/anchor.js
This addreses some of the issues discovered in #738 
Currently, when using MediumEditor's anchor button with the `targetCheckbox` and/or `customClassOption` options enabled, the checkboxes will be displayed inside the anchor form whenever creating a link.
However, if the user checks either of these checkboxes, the next link they create will still have the checkboxes checked by default (since the checkboxes are not cleared when displaying the anchor form).
This PR fixes 2 issues:
1. The state of the checkboxes will be cleared each time the anchor form is displayed.  This way, the checkboxes will always be 'unchecked' when creating a new link.
2. When editing an existing link (via clicking the anchor-preview popover), the checkboxes will be checked/unchecked based on whether the link being …
> Ensure anchor target + class checkboxes are initialized correctly

- src/js/extensions/paste.js
When you use `cleanPaste` with a multiline pasted text it will do some custom stuff related to paragraph.
But it will also cleanup *block elements*. The problem is that it cleans block element of the WHOLE content (if you do not have a selection, the selected element will be the editor), not only the pasted one. So I moved the code that performs this cleanup inside `pasteHTML` where I have a node so I can cleanup ONLY the pasted content.
Problem appear when using external library that update MediumEditor content adding custom html, like medium-editor-insert-plugin. It adds div, figure, etc .. so if the pasted content was multiline, the cleanup will remove all this tags (according to my `cleanTag` attributes).
Also, we previously added a new line after pasted content. Why ? I think when …
> Cleanup only pasted elements

- spec/selection.spec.js
- src/js/selection.js
There is logic which handles the case where we import/export the current selection, but the selection occurs after 1 or more empty paragraphs.  We determine where to position the cursor by tracking how many empty paragraphs there are between the last piece of text, and where the selection begins.
However, this logic was assuming that in the case where we need to import the selection, the selection is always collapsed (just a cursor).  Because of this, we were unable to import/export selections correctly at the beginning of paragraphs.  
This also manifested itself such that we were unable to create links at the beginning of paragraphs (ie #738).
This PR removes the code which collapsed the selection when importing selections that occur after empty paragraphs.
> Fix for #738 issue with importSelection after empty paragraphs

- spec/anchor.spec.js
- src/js/extensions/anchor.js
This fixes #751 
When the user clicks the 'anchor' button, we attempt to find an existing anchor within the selection.  If there is one, we 'unlink' that anchor, otherwise we display the anchor form an allow them to create a link.
There was a bug in the code that tries to find the existing link.  It was incorrectly looking for the first text node within the parent selection node, which manifested itself as being unable to create a link when a link appeared as a previousSibling of a text node which was being selected.
> Fix #751 - issue with finding anchor when clicking anchor button

- spec/textarea.spec.js
- src/js/core.js
This should fix #711
All attributes from the textarea are now re-created when the medium-editor is created, except attributes that are already attached to the div. Should I remove this condition?
Should we enable that using an option or by default it's fine?
> Recreate all attributes when using textarea

- spec/anchor.spec.js
- src/js/selection.js
Fix issue #757 where the selection import would ignore the embedded
information about empty paragraphs before it and would import a
selection as multiline that should have been contained at the beginning
of a paragraph.
Also restore a `range.collapse(true)` that was used for an MSIE-specific
fix unrelated to restoring these types of selections.
> Fix #757, issue where selection restored too large

- spec/anchor.spec.js
- spec/placeholder.spec.js
- src/js/core.js
- src/js/util.js
This PR fixes some issue with inserting links and helps work around some existing issues with selection in Internet Explorer.  It also fixes a seemingly random test failure that started occurring in Chrome on Windows.
1. Fix the current test failure happening in MSIE in MediumEditor version 5.5.3.
2. Whenever attempting to create a link within a single text node, just fall back to the browser's default `document.execCommand('createLink', ...)`.
* This fixes an issue where the top-level `<p>` tag was getting removed in MSIE when a link was created inside that `<p>` who only had a single text-node
* When selection starts at the beginning of a text-node, MSIE still says the `range.startContainer` is a parent of the text-node, and thus the `commonAncestorContainer` is also a parent of the …
> Fix anchor + selection inconsitencies in IE

- src/js/extensions/paste.js
- src/js/util.js
Chrome add comments when you paste content with html enabled.
It's not really a problem if you paste your content once. But if you past it twice, everything after the pasted content will be removed. I guess Chrome find its _fragment_ comments again and erase them ...
Here is a more revelant gif of the problem:
Should I add some tests specific to Chrome?
> Cleanup comment created by Chrome

- spec/anchor.spec.js
- spec/events.spec.js
- src/js/core.js
- src/js/events.js
I found that editableInput could be fired twice in the situation where you create a link with a target=_blank attribute. It fires once when the document execCommand `insertHTML` is called, and a second time after the link is modified.
This also had the result of editableInput being fired before medium restored the selection after calling `insertHTML`, which put the selection out of sync with what it should have been.
This PR changes the createLink command to suppress firing of the `editableInput` event until after the HTML is inserted and the selection is restored, plus after any changes to the link attributes have been made in the DOM.
> Fire editableInput only once, at the end of link creation

- spec/content.spec.js
- src/js/events.js
- src/js/util.js
This PR is fix for disableReturn and disableDoubleReturn.
I can't use return-key when I use disableReturn option, but I can use enter of emacs key bindings(ctrl + m).
> Added enter of emacs key bindings to handleKeydown

- spec/anchor.spec.js
- spec/selection.spec.js
- src/js/selection.js
This fixes an issue when saving selection if the cursor is at beginning of a paragraph, but not preceded by empty paragraphs.
We track whether the cursor is at the beginning of a paragraph that has empty paragraphs before it by counting the empty paragraph and storing in the selection data.  However, if the paragraph did not have empty paragraphs in front of it, we didn't store anything, which made the selection get set to the end of the paragraph before it, rather the beginning of the paragraph it should be within.
The fix is to always track if the cursor is at the beginning of a paragraph, and set `emptyBlocksIndex` to `0` if there are no empty paragraphs before it.  Before, this case would have just left `emptyBlocksIndex` as undefined.
This manifested itself in the re-opened issue for …
> Fix #757 Track beginning of paragraph in exportSelection

- spec/selection.spec.js
- src/js/selection.js
- src/js/util.js
This PR includes the changes for #761, so that PR should be merged first.
This fixes #732 
This PR fixes a variety issues around preserving selection within nested block elements (ie `<li>` inside of `<ul>`)
1. When a selection starts at the beginning of a block element, we need to do some special handling to ensure the cursor is placed there when selection is restored (vs the selection be inserted at the end of the block element before it).
2. This change accounts for any type of block element other than `<div>`.  The previous code only accounted for block elements that could be generated by the built-in MediumEditor commands.
3. This change expects that block elements can occur anywhere in the DOM, and can be nested within other block elements. The original code assumed there wouldn't …
> Fix #732 - Fix issue with selection inside nested block elements

- spec/paste.spec.js
- src/js/extensions/paste.js
Kind of revert #746 (with a better solution !)
I made some changes in `pasteHTML` which breaks compatibility with previous extension that might used `pasteHTML` directly (like https://github.com/yabwe/medium-editor-tables).
I now use a work around to be sure that the block element cleanup only apply to the pasted content instead of the whole document (if no content were previously selected).
And I added tests to avoid future regression … (mostly related to yabwe/medium-editor-tables#15)
> Fix clean paste

- Gruntfile.js
Enable saucelabs tests to run for:
* Latest Chrome on Windows 10
* Latest Firefox on Windows 10
* IE11 on Windows 10
> Enable Saucelabs tests for Windows 10

- spec/textarea.spec.js
- src/js/core.js
When medium replaces textareas with divs, the medium-editor-textarea-id attributes used to link them together is not unique across the whole page. If you need to use multiple editor instances (for example, if you have a dynamic page, or if your are binding the editor inside some other component framework), the syncing between textarea and editor doesn't work if there are multiple editors.
This change simply re-uses the existing unique div id to make the medium-editor-textarea-id value unique in the page.
> Multiple medium instances cannot be used in a single page with textareas

- spec/auto-link.spec.js
- src/js/extensions/auto-link.js
This fixes an issue where auto-link was not finding valid urls within list items.
Auto-Link was iterating over `<p>` tags and finding text within them which could be a link.  By instead iterating over all possible block elements, it was able to find valid urls within any of our defined block elements, including list items.
> Fix auto-link within list items

- spec/util.spec.js
- src/js/util.js
This fixes #748 which was a bug within the custom `insertHTMLCommand()` utility method which runs on browsers which don't support `insertHTML` natively through `document.execCommand()`.
The custom code for `insertHTMLCommand()` assumed that the editor would always have some content.  In the case where the editor is completely empty (no child nodes), the code will now create a temporary empty textnode which will get replaced by the incoming HTML.
> Fix #748 - Don't delete editor inside util.insertHTMLCommand

- spec/keyboard-commands.spec.js
- src/js/extensions/keyboard-commands.js
`alt` options was added in 5.4.0 (see #727).
Every custom keyboardCommands config since this version will get a `data.alt` as `undefined` when testing if <kbd>alt</kbd> is pressed. Config example before 5.4.0:
```js
{
command: 'bold',
key: 'B',
meta: true,
shift: false
},
```
And then `undefined === false` is falsy so the command will never be fired.
I don't know if we need this extra `if` or an extra check in the following `if`.
If you guys agree about that solution, I'll add some tests after.
> Handle backward compatibility with <= 5.4.0

- spec/anchor.spec.js
- spec/buttons.spec.js
- spec/events.spec.js
- spec/extension.spec.js
- spec/placeholder.spec.js
- src/js/core.js
- src/js/extensions/placeholder.js
This PR covers a bit of a re-write of how the placeholder extension handles hiding/showing the placeholder text.
The new placeholder extension leverages the `editableInput`, `focus`, and `blur` custom-events provided by the internal MediumEditor code to better detect when the placeholder text should be hidden or shown.
By listening to `editableInput`, the extension is also able to detect when calls to `setContent()` happen, which fixes #768 .
By listening to `focus`, `blur`, and `editableInput`, and checking the value of the `placeholder.hideOnClick` option, the extension is also able to prevent showing the placeholder incorrectly while clicking buttons on the toolbar, which fixes #783 
Other Issues Resolved:
* Since the placeholder extension now uses `editableInput`, MediumEditor will …
> Fix #768 + Fix #783 + Simplify and Fix Placeholder Extension

- src/js/util.js
Browsers expose a `Node.contains()` method ([MDN](https://developer.mozilla.org/en-US/docs/Web/API/Node/contains)) which checks if one node is contained with another.
We should use this function inside our `MediumEditor.util.isDescendant()` helper method as it will be more efficient to rely on the browser for this check.
However, browsers don't consistently return `true` for this if the child node being checked for is a text-node, so we'll need to feature detect, and use our old while-loop fallback in cases where it's not supported.
> Make util.isDescendant() more efficient when browser allows for it

- demo/auto-link.html
- spec/auto-link.spec.js
- src/js/extensions/auto-link.js
This fixes #790 where auto-link was creating links that spanned across consecutive list-items.
The root cause is the way auto-link looks for elements with text that may contain valid urls which we should convert into links.  Previously it was searching for all elements in the `MediumEditor.util.blockContainerElementNames` array, which included elements like `ol`, `ul`, and `dl`. However, the text content of these elements is just the text within each of their child list-items concatenated together without new-lines.  The result was if concatenating two or more list-items together resulted in a valid url, the code would attempt to create a link which spanned those multiple list-items.
A simple fix for this is to filter out the specific elements we want to ignore when checking for …
> Fix #790 - Don't auto-link across multiple list-items

- spec/util.spec.js
- src/js/util.js
2 Things were broken by #792:
1. When 2 elements that are equal are passed as arguments, `isDescendant()` used to return false.  However, the native `node.contains()` will return true in this case.  This makes the behavior inconsistent depending on the browser or support, so catching this case and falling back to the original behavior
2. When the `parent` is a textnode, the current implementation would throw an exception, since `.contains()` is undefined on textnodes.
> Fix some breaks in isDescendant that were introduced by #792

- spec/auto-link.spec.js
- spec/util.spec.js
- src/js/extensions/auto-link.js
- src/js/util.js
My original attempt to fix auto-link issues within nested block elements (ie `<li>` elements inside of `<ol>` elements) was very targeted towards specific common cases where we know we don't want to auto-link the `textContent` of the element, but rather auto-link the content of its children (`'ol', 'ul', 'dl', 'table', 'tbody', 'tfoot', 'tr'` elements).
However, there are still many other cases where we don't want to auto-link the `textContent` of a block element, since it can have other block elements:
```html
<div>
<blockquote>
<ol>
<li>www</li>
<li>.example.com</li>
</ol>
</blockquote>
<div>
```
In this example, the auto-link code would try to create a link around the entire `<ol>` element, since the code would first find the `<blockquote>` and then see that its textContent …
> More autolink fixes

- spec/anchor.spec.js
- src/js/extensions/anchor.js
Fix for https://github.com/yabwe/medium-editor/issues/824
1. Squashed multiple commits into 1 commit.
2. trimmed the url.
3. Removed unnecessary conditional check with trimmed values as now we are initialising  it with the trimmed values itself.
> removed trailing white spaces from the link and undid the changes in dist files made in earlier commit

- OPTIONS.md
- README.md
- spec/anchor-preview.spec.js
- src/js/extensions/anchor-preview.js
New option as discussed here: https://github.com/yabwe/medium-editor/issues/825
> New anchor preview option to show when toolbar is visible

- spec/anchor.spec.js
- src/js/extensions/anchor.js
Updated checklink function to check if a link is a valid phone number. The test is quite liberal to allow for US and European phone numbers.
If the string is recognized as a phone number, prepend  'tel:'.
otherwise perform previous https / ftps / rtmpt / mailto check.
> Updated checklink function to check if a link is a phone number

- src/js/core.js
Is there a reason why a basic ```input``` event is used for textarea syncing? [My plugin](https://github.com/orthes/medium-editor-insert-plugin) fires your custom ```editableInput``` event everytime an image is added/deleted and this causes a problem when using textareas, because ```input``` event is never fired and textarea is not sycned (https://github.com/orthes/medium-editor-insert-plugin/issues/238).
```editor.serliaze()``` returns correct content, ```editor.subscribe('editableInput')``` is fired, but textarea is not synced.
I also noticed that the editor usually never fires ```input``` event or listens for it. Instead you always use ```editableInput```.
So in this small PR I simply replaced ```input``` event with ```editableInput```.
> Use editableInput instead of input event for textarea syncing

- spec/content.spec.js
- src/js/core.js
- src/js/util.js
Fixed https://github.com/yabwe/medium-editor/issues/143
Upon pressing backspace key at the start of the ```blockquote``` tag, changes it to ```p``` tag.
Upon pressing backspace key at any position other than start of the element, default action continues.
> fixed 143 👊

- spec/util.spec.js
- src/js/util.js
This fixes an issue that caused a `child.querySelectorAll is not a function` error when using `autoLink: true` on content with comments.
Closes https://github.com/yabwe/medium-editor/issues/897
> Fix auto linking with comments

- spec/buttons.spec.js
- src/js/core.js
This PR trims trailing whitespace and newlines from image urls before inserting them into an `<img>` tag.
**The issue this PR fixes**:
If the src has trailing newlines (it's pretty easy to accidentally select an empty line after the url) browsers display the image just fine, but most email clients do not (i.e. gmail) if the content is used in an email later.
> Trim src when using the image toolbar button

- spec/anchor.spec.js
- spec/helpers/util.js
- spec/selection.spec.js
- spec/toolbar.spec.js
- spec/util.spec.js
- src/js/core.js
- src/js/extensions/toolbar.js
- src/js/selection.js
- src/js/util.js
Currently, medium-editor does not sufficiently handle exporting/importing selections that contain only an image (it's kind of supported in some browsers, but completely busted in IE). Images are a specific problem because:
1. `<img>` elements are not text-nodes _(the code only handled selections that span 1 or more text nodes)_
2. `<img>` elements are elements that will never have children _(the code ignored any element without children)_
3. `<img>` elements have empty textContent _(the code depends on content having length so it can store the beginning and end of a selection)_
medium-editor handles exporting/importing selections based on the number of characters and paragraphs are before and after the selection.  So, if the selection contains only an image, when attempting to restore the …
> Fix issue with image-only selections

- src/js/extensions/anchor-preview.js
- src/js/extensions/toolbar.js
Issue https://github.com/yabwe/medium-editor/issues/138 is closed but is still occurring.
Fixed it by positioning the toolbar and anchor preview on the rhs when it doesn't fit.
> fixed issue 138

- README.md
- spec/paste.spec.js
- src/js/extensions/paste.js
Allow an Array of `cleanReplacements` to execute before builtin replacements.
See #925.
> Pre clean replacements

- spec/helpers/util.js
- spec/selection.spec.js
- spec/util.spec.js
- src/js/selection.js
- src/js/util.js
While investigation #935, I found a variety of issues:
* If a selection began in the first `<p>` after some lingering white space, exporting and then importing the selection was busted, as in the selection would not be restored correctly. The result was #935, where trying to create a link within that `<p>` caused an exception to be thrown.
* Previously, `util.getClosestBlockContainer()` and `util. getTopBlockContainer()` would return `false` if the passed in parameter was a node without any block containers other than the editor element.  Thus, the code could return `false` when it really should have been returning the actual editor element (since the editor element is the 'block container' that contains everything).  Our code expected there to be an element, an instead was getting …
> Fix #935 - Fix a variety of issues related to selection imports/exports

- spec/util.spec.js
- src/js/util.js
Looking at our code coverage numbers, I found a method that is not referenced by our code anymore (`MediumEditor.util.getFirstTextNode()`).  We should get rid of this function since it's not used, however since it changes the API we'll have to settle with just deprecating it for now and remember to remove it in 6.0.0.
Since it's going to be around, and could potentially get used by other code moving forward, we should have coverage of this function.  I've added a few test cases to have 100% coverage of the helper method.
> Deprecate util.getFirstTextNode

- spec/placeholder.spec.js
- spec/selection.spec.js
- spec/util.spec.js
Some of our tests had broken references to images, this should be fixed now (and there shouldn't be any 404s when running tests in a browser).
> Fix some bad image references in tests

- CUSTOM-EVENTS.md
- Gruntfile.js
- README.md
- spec/anchor-preview.spec.js
- spec/anchor.spec.js
- spec/buttons.spec.js
- spec/content.spec.js
- spec/core-api.spec.js
- spec/extension.spec.js
- spec/fontname.spec.js
- spec/fontsize.spec.js
- spec/helpers/util.js
- spec/keyboard-commands.spec.js
- spec/paste.spec.js
- spec/placeholder.spec.js
- spec/selection.spec.js
- spec/setup.spec.js
- spec/toolbar.spec.js
- spec/util.spec.js
- src/js/core.js
- src/js/events.js
- src/js/util.js
Fixes for #771
* Fixed 51 failed tests!
* All tests are now run on Edge in Windows 10 (via SauceLabs)
Changes & Stuff I've learned:
* Enabled Edge browser testing in SauceLabs!
* For `<a>` tags, Edge seems to add a protocol to the beginning of urls within the `href` attribute, even when one isn't specified.  Had to update the tests to account for this.
* Edge seems to handle 'indent' for `<blockquote>` tags the same way Firefox does, so expand special handling to include Edge (which means browser sniffing :disappointed:)
* Edge's implementation of `insertHTML` for `document.execCommand()` appears to have some bugs.  The first big part of this is to use our existing fallback for `insertHTML` even though Edge says it supports it.
* For our test cases in Edge, manually triggering a 'focus' …
> Edge Support: Fixes to medium-editor and test cases for Edge

- spec/anchor.spec.js
- spec/util.spec.js
- src/js/core.js
- src/js/util.js
Added a function `setTargetSelf` along the lines of `setTargetBlank`.
It is called whenever target is not suppose to be blank. The need to do this came up because of #939 . It worked well on all browsers except Firefox. So had to specifically remove target blank from the anchor tags. And one of the way I think to remove is to set it to `_self`.
> fix for #939 🔨

- spec/content.spec.js
- src/js/core.js
This is a continuation of @ryandh 's work in #835.
When the cursor is directly within a block element (ie `<figcaption>`, `<h1>`, etc.), when the code calls `document.execCommand('formatBlock', null, 'p')` it did some unsavory things to the html, and in the case of `<figcaption>` in Firefox, it actually would keep moving the cursor to the beginning of the line after each keystroke, which presented your text in reverse order.
> Fix #834 - Don't call formatblock when cursor is within block element

- Gruntfile.js
Just a cosmetic change. I've noticed that we're not testing against the latest OS X 10.11 which causes that we're not testing against the latest Safari 9, but against Safari 8 ([the only version supported in OS X 10.10 by Sauce Labs](https://saucelabs.com/platforms/#osx))
> Update OS X to 10.11 in Sauce Labs

- spec/anchor.spec.js
- src/js/extensions/anchor.js
- src/js/extensions/form.js
- src/sass/components/_toolbar-form.scss
For better forms customization with CSS it's better to handle show|hide
state by class.
I've appended additional class for visible form and remove inline style
modifications.
Also I't moved show/hide form functional to form implementation.
> Remove hardcoded inlined display style for anchor editor

- spec/auto-link.spec.js
- src/js/extensions/auto-link.js
Only re-enable AutoUrlDetect when all auto-link instances have been destroyed -- created an `isLastInstance()` function which checks if all other Medium Editor instances with auto-link enabled have been destroyed.
Fixes #961
> Destroy ie autolinks

- spec/keyboard-commands.spec.js
- src/js/extensions/keyboard-commands.js
Allows you to set a function as "command" option for keyboard commands.
Use case: triggering custom buttons using keyboard shortcuts.
Example config:
```js
var options = {
toolbar: {
buttons: [
'b',
]
},
keyboardCommands: {
commands: [
{
key: 'B',
meta: true,
shift: false,
alt: false,
command: function() {
editor.getExtensionByName('b').button.onclick();
},
}
]
},
extensions: {
'b': new MediumButton({
label: '<i class="fa fa-bold"></i>',
start: '<strong>',
end: '</strong>'
})
}
}
```
> Use function as keyboard command

- src/js/events.js
`Events.updateInput()` is called on every `keypress`. But when the editor contains large amount of data, `innerHTML` becomes very expensive - performance-wise. This simple PR cuts the lag time to half by calling `innerHTML` only once, not twice.
> Use innerHTML in Events.updateInput() function only once to improve performance

- OPTIONS.md
- README.md
- spec/anchor.spec.js
- src/js/extensions/anchor.js
Converts all instances of spaces to url friendly %20 if linkValidation for anchors is enabled. Example in screenshot mirrors same test case from the issue.
Fixes #1014
> Fix 1014 - Convert spaces to %20 in links if linkValidation is true for the anchor extension

- spec/anchor.spec.js
Turns out, Chrome, IE, and Edge automatically encode urls when you set them as an href of an `<a>` tag.  However, Firefox, Safari, and our version of PhantomJS don't automatically encode these urls.
This means the test that was verifying that the href is NOT encoded when `linkValidation` is set to `false` would pass in PhantomJS, Firefox, and Safari, but was failing in the other browsers.
This change updates the test case to check for the value of the encoded/not-encoded url before it actually gets set into the html.
> Fix failing anchor test

- API.md
- spec/events.spec.js
- src/js/core.js
- src/js/events.js
This small PR consists of two minor improvements:
- Add support for function chaining in event functions (`on`, `off`, `subscribe`, `unsubscribe`, `trigger`), so you can write this:
```javascript
this
.on(/*...*/)
.on(/*...*/)
.on(/*...*/);
```
... instead of this:
```javascript
this.on(/*...*/);
this.on(/*...*/);
this.on(/*...*/);
```
- Allow multiple targets when adding or removing event listeners:
```javascript
var elements = document.getElementsByClassName('some-class');
this.on(elements, 'click', listener);
```
... instead of this:
```javascript
var elements = document.getElementsByClassName('some-class');
this.on(elements[0], 'click', listener);
this.on(elements[1], 'click', listener);
```
> Support function chaining in event functions and allow multiple targets when adding event listeners

- spec/content.spec.js
- src/js/core.js
From @nextend in #1020:
> In Firefox if the editable is a node without children, then NS_ERROR_FAILURE: error thrown for every keyup until it gets a child node. 
> Issue: https://github.com/yabwe/medium-editor/issues/994
This completes #1020 by adding a test to verify the fix.
In addition to adding a new test, I also rearranged the tests in `content.spec.js` to be grouped a bit better.
> Fix #994 - Prevent Firefox NS_ERROR_FAILURE: on keyup

- CUSTOM-EVENTS.md
- spec/anchor-preview.spec.js
- spec/toolbar.spec.js
- src/js/extensions/anchor-preview.js
- src/js/extensions/toolbar.js
This PR fixes #1047 where clicking on an anchor preview when using the `showWhenToolbarIsVisible` option doesn't edit the link but instead navigates away from the page.
The issue was rooted with the toolbar manually calling into the anchor-preview's `hidePreview` event whenever the toolbar was being updated.  This flow didn't account for the `showWhenToolbarIsVisible` option and resulted in some improper handling of the click.
Now, instead of the toolbar calling directly into the anchor-preview extension, the toolbar & editor will emit a `positionedToolbar` custom event, which the anchor-preview can subscribe to.  This will allow the anchor-preview to handle the `showWhenToolbarIsVisible` option properly and fix the bug.
>  Fix #1047 - Add 'positionedToolbar' custom event

- src/sass/medium-editor.scss
#1043 introduced `word-break: break-all;` which unfortunately did more harm than good.
It splits words at the end of a line even if it's not needed: 
This small PR just replaces this wrong behavior with much safer `word-wrap: break-word;`
Fixes #1057
> Fix #1057 - replace break-all with break-word

- API.md
- demo/button-example.html
- spec/core-api.spec.js
- src/js/core.js
- src/js/extensions/WALKTHROUGH-BUTTON.md
| Fixed tickets    | #942 
#942 pointed out that the button building walkthrough results in a button that doesn't update a `<textarea>` when the highlight button is clicked.
In order to allow any extension or user to have the editor function as expected when its html changed, I added a `checkContentChanged` method which will check for any changes to the editor and trigger the `editableInput` event if the content has changed.
I've also updated the button example and button tutorial to use this new method, which fixes #942
> Fix #942 - Expose method to check for changes to html

- src/js/events.js
I ran into an issue that after manually adding elements to the editor (through addElements), and later deleting them again there (through removeElements) was a TypeError being thrown.
It appears that contentCache is not set when only using dynamically added elements, thus while removing that element it will run into an error resulting the element not being removed properly.
This checks if contentCache is set.
> Fix null pointer during the cleanupElement event

- spec/core-api.spec.js
Some newly added tests depended on attaching spies to `document.execCommand`, but in IE & Edge the code will create a wrapper around `document.execCommand` thus breaking these new tests.
I've updated the tests to workaround this and disable the custom IE code when the tests run.
> Fix failures from new tests in IE & Edge

- spec/core-api.spec.js
- src/js/core.js
| Deprecations?    | yes
Deprecate usage of `.url` for `createLink()`, and usage of `.size` + `.name` for `fontSize` and `fontName` command respectively when calling `.execAction()`.
Also, add test to ensure `.url` is properly supported for backwards compatibility until 6.0.0 is released.
> Deprecate some execAction and createLink options

- spec/anchor-preview.spec.js
- src/js/extensions/anchor-preview.js
| Fixed tickets    |  #1071 
By default anchor preview will be shown on empty links (href='' or href="#something"). This feature can be turned of when  showOnEmptyLinks = false in extension settings.
--
> Allow preview to be shown on empty links

- spec/paste.spec.js
- src/js/events.js
- src/js/extensions/paste.js
| BC breaks?       | potentially
| Fixed tickets    | #1098
The new paste handling code injects a temporary element to capture keyboard pastes.  By introducing this new element, which is not part of the editor element, it prevented the `paste` event from being triggered on the editor, which would mean the `editablePaste` event also would not be triggered.
The fix was to manually trigger the `editablePaste` event whenever keyboard paste occurs.
Since some of this triggering happens within a `setTimeout()` after the paste event, we won't always have a valid event object to use when manually triggering `editablePaste`.  So, …
> Fix #1098 - editablePaste not triggering on keyboard paste

- API.md
- README.md
- spec/core-api.spec.js
- spec/elements.spec.js
- spec/textarea.spec.js
- src/js/core.js
Introduce new static method `MediumEditor.getEditorFromElement(element)` which returns the corresponding instance of MediumEditor provided an editor element.
This allows for developers to not have to store instances of MediumEditor provided they can get access to the editor elements themselves from the DOM.
Internally, it leverages the already existing global array of instance of MediumEditor by adding a data attribute to each editor element that specifies which index in the global array the instance is located.
> Expose method for getting editor instance from an element

- API.md
- README.md
- spec/core-api.spec.js
- src/js/core.js
| Fixed tickets    | #492
Expose simple helper for retrieving content from a MediumEditor instance as requested in #492.  The `getContent()` method is a natural compliment to `setContent()` and behaves as expected based on the behavior of `setContent()`.
> Add getContent method (Fix #492)

- API.md
- README.md
- spec/core-api.spec.js
- spec/textarea.spec.js
- src/js/core.js
| Fixed tickets    | #719 
The goal of this change was ensure that when a `<textarea>` element within a form is reset, that the editor `<div>` created by the editor is also reset back to its initial value.
To accomplish this, this change set also introduces a new `resetContent()` method for resetting any element back to its initial value when the editor was initialized or when the element was first added to the editor.
> Fix #719 - Respect form.reset for textarea elements within forms

- spec/anchor-preview.spec.js
- src/js/extensions/anchor-preview.js
| Fixed tickets    | #1105 
When the anchor-preview was clicked, it was displaying 'undefined' in the anchor form, this was caused by a previous change where we changed over from using `opts.url` to `opts.value` to standardize on how we pass arguments into `document.execCommand()`.  Updating the anchor-preview was missed during that change.
There surprisingly isn't a test ensuring that when you click the anchor-preview, the `href` of that link is pre-filled into the anchor form, I've updated an existing test to assert that this happens.
> Fix #1105 - Fix bug with anchor-preview when clicked

- spec/extension.spec.js
- src/js/events.js
- src/js/extension.js
- src/js/extensions/README.md
- src/js/extensions/anchor-preview.js
- src/js/extensions/toolbar.js
| Deprecations?    | yes
| Fixed tickets    | #830
Currently, if any extension render an element on the page, if the user clicks on that element it counts as a click on an element outside of the editor, which causes the editor to `blur` and potentially hide the toolbar altogether.
This change set introduces a new `getInteractionElements()` method that any extension can implement.  This allows extensions to let MediumEditor know that it has created HTML elements that, when clicked, should not count as external interactions, and thus should not cause the editor to `blur` when being interacted with.
> Support any extension preventing blur of editor (Fix #830)

- spec/init.spec.js
| New tests added? | changed
Now in Chrome 51, `NodeList` objects have defined a `forEach` method.  There was a test that attempted to confirm that `forEach` wasn't defined on a `NodeList` to ensure that code that had depended on `forEach` was safely executing.
I've updated the test to assert that the `NodeList` is not an `Array` instead.
> Fix test failure in Chrome 51

- spec/elements.spec.js
- spec/textarea.spec.js
- src/js/core.js
- src/sass/medium-editor.scss
| New tests added? | updated
Fixed a slow CSS selector that our linter was complaining about:
```terminal
Linting dist/css/medium-editor.css...ERROR
[L209:C1]
WARNING: Unqualified attribute selectors are known to be slow. Unqualified attribute selectors are known to be slow. (unqualified-attributes) Browsers: All
```
To fix this, we can add a `medium-editor-element` class to the editor element, and update the CSS selector to use that instead of an unqualified attribute selector.
> Fix slow CSS selector

- OPTIONS.md
- README.md
| Fixed tickets    | Created in response to #1121 
Improving documentation for `toolbar.realtiveContainer` option in README and adding missing documentation to OPTIONS.md
> Improve documentation for toolbar.relativeContainer option

- spec/placeholder.spec.js
- src/js/extensions/placeholder.js
- src/sass/components/_placeholder.scss
| Fixed tickets    | #234 
In Firefox, when the editor element is completely empty (including when it doesn't have `<p><br /></p>`), the absolutely positioned pseudo-element used for a placeholder affects where the blinking cursor appears once the editor is focused.
When the pseudo-element is positioned `relative` in this case, everything renders as expected.  However, when positioned `relative`, the placeholder renders incorrectly for other cases and renders incorrectly in other browsers.
This fix ensures that only in firefox, and only when the editor element is completely empty, the …
> Fix #234 - Cursor rendering incorrectly in firefox

- src/wrappers/start.js
| Fixed tickets    | 1123
Bug-ID #1123, fixes issue with electron environment.
> #1123 Fixes issue with electron environment

- CUSTOM-EVENTS.md
- spec/dyn-elements.spec.js
- spec/paste.spec.js
- spec/placeholder.spec.js
- src/js/core.js
- src/js/events.js
- src/js/extensions/paste.js
- src/js/extensions/placeholder.js
| Fixed tickets    | Fixing issue related to discussion in #1120 
1. Expose new `addElement` and `removeElement` custom events for extensions to listen to
2. Fix issue with paste-handler introduced by 8bd8f8f where right-click paste isn't getting the actual paste event object so it wouldn't have access to the clipboard data.
* As part of the fix, paste-handler now needs to know when elements are added to the editor
3. Fix issues with placeholder extension where dynamically added elements are not getting a placeholder, and dynamically removed elements aren't being cleaned up.
> Fixes for paste and placeholder extensions + add/remove element events

- spec/placeholder.spec.js
- src/js/extensions/placeholder.js
> #1127 | Placeholder is visible when only empty table is in Editor.

- spec/anchor.spec.js
- src/js/extensions/anchor.js
Allows hash links, e.g. `#fragment-identifier`, when `linkValidation` is set to `true`. This was brought up in this discussion: https://github.com/yabwe/medium-editor/issues/714
> Make linkValidation allow hash links

- demo/absolute-container.html
- spec/anchor-preview.spec.js
- spec/toolbar.spec.js
- src/js/extensions/anchor-preview.js
- src/js/extensions/toolbar.js
| Fixed tickets    | #224, #857
Fix positioning of a toolbar and an anchor preview when `elementsContainer` has `position: absolute` or `position: fixed`.
If `elementsContainer` is `absolute` or `fixed`, it will calculate positions relative to this element instead of window.
I also added a demo `demo/absolute-container.html` which demonstrates this behavior.
> Fix #224 and #857 - toolbar in absolute container

- spec/content.spec.js
- src/js/core.js
| Fixed tickets    | #294, #1054
We had this reported a bunch of times. When you place a caret at the end of a blockquote and press enter, a new blockquote is created instead of a plain paragraph and you have to press backspace to get rid of it. This is not a standard behavior. When you do the same with other block elements (h1, h2...) you will get a paragraph as expected. For some reason, this doesn't work with blockquotes.
Also when you try it in other "standard" editors (Word, Pages, Google Docs...), it behaves as expected - on enter you will get rid of the current "style" and start a new plain …
> when caret is at the end of blockquote and you press enter, create paragraph, not another blockquote

- src/js/extensions/README.md
Adds an example of a custom button extension.
--
> add external button example

- spec/content.spec.js
- src/js/core.js
| Bug fix?         | more or less
| Fixed tickets    | -
Most users don't know the difference between backspace and delete. So if they create a paragraph as the first element in the editor and they want to delete it, they place caret to the paragraph and press backspace. Which does nothing. In order to delete that paragraph you need to press delete / fn+backspace on mac, or move caret to a beginning of next paragraph and press backspace there.
I've seen people struggling with this, so this PR solves this problem. If a caret is in the first and empty paragraph and you press backspace, it will do delete instead - it will …
> remove first empty paragraph on backspace

- OPTIONS.md
- README.md
- spec/paste.spec.js
- src/js/extensions/paste.js
- src/js/util.js
| Bug fix?         |no
| BC breaks?       |no
| Deprecations?    |no
| Fixed tickets    | #1141
Added unwrapTags option to paste extension, which instead of removing the tag element entirely, removes the tag element but preserves its children. 
See issue #1141 for detailed description.
I added a new test case and I did some manual testing with `demo/clean-paste.html`.
--
> Added unwrapTags option to paste extension

- src/sass/themes/flat.scss
| Fixed tickets    | #1156 
For the flat theme, the color of the placeholder text ended up being white, which made it unreadable.
I've update the text color of the placeholder text to be a lighter version of the green the flat theme uses for the toolbar (this makes is similar to the bootstrap theme).
> Fix #1156 - placeholder text color in flat theme

- src/js/events.js
| Fixed tickets    | comma-separated list of tickets fixed by the PR, if any
```js
//content in iframe
var doc = content.ownerDocument;
var editor = new MediumEditor(content, {
.........
contentWindow: doc.defaultView || doc.parentWindow,
ownerDocument: doc
});
```
if convert iframe's div to editor,it will throw error. 
--
> fixed iframe div

- src/js/extensions/README.md
Adding new external extensions into the extensions README, checking with owners to make sure they're ok with this before merging and adding to the landing page.
@cruzanmo any objections with us linking [MediumEditor Phrase](https://github.com/nymag/medium-editor-phrase) in the documentation and on our [Landing Page](https://yabwe.github.io/medium-editor/#extensions)?
@davideanderson any objections with us linking to [MediumEditor Toolbar States](https://github.com/davideanderson/medium-editor-toolbar-states) in the documentation and on our [Landing Page](https://yabwe.github.io/medium-editor/#extensions)?
@dazorni any objections with us linking to [MediumEditor AutoFocus](https://github.com/dazorni/medium-editor-autofocus) in the documentation?
@jawish any objections with us linking to …
> Add new extensions to extensions README

- spec/anchor.spec.js
- src/js/extensions/anchor.js
| Fixed tickets    | https://github.com/yabwe/medium-editor/issues/1218
This PR adds some functionality to linkValidation: an URL's unencoded path and query are encoded, and encoded path and query are not encoded.
--
> support encoded urls

- src/wrappers/start.js
| New tests added? | no, not sure if needed
| Fixed tickets    | #1221
Fix detection of commonJS environment without electron as described in the comments in #1221
Please advise on if refactoring or new test cases are needed.
> fix #1221 commonJS/electron environment detection

- src/js/extensions/auto-link.js
Efficiency: Create RegEx-object only once.
> Efficiency: Compile RegEx once

- src/js/events.js
| Deprecations?    |no
| Fixed tickets    | [#1151](https://github.com/yabwe/medium-editor/issues/1151)
--
`events.detachDOMEvent()` is attempting to run `forEach` on a null value.  This specifically occurs when you have a word or block of words formatted as a link.  Trying to format that same text block a second time triggers the error consistently.
> Fix for #1151

- dist/js/medium-editor.js
I just made the code more simple. It works exactly the same but now it's more readable, and the cpu has to make fewer calculations.
Let's compare:
textIndexOfEndOfFarthestNode = currentTextIndex + (newNode || currentNode).nodeValue.length +
(newNode ? currentNode.nodeValue.length : 0) -
1;
If newNode is defined, then it resolves to:
textIndexOfEndOfFarthestNode = currentTextIndex + newNode.nodeValue.length +
currentNode.nodeValue.length - 1;
If newNode is undefined, it resolves to:
textIndexOfEndOfFarthestNode = currentTextIndex + currentNode.nodeValue.length - 1;
Then, …
> Save some CPU calculations

- js/medium-editor-site.js
Broken navigation of themes carousel on site.
- go to http://yabwe.github.io/medium-editor/
- scroll to `Themes` section
- click on links to change theme preview
---
This fix was tested on macOS Sierra 10.12.1 (16B2659) in:
- Google Chrome 55.0.2883.95
- Firefox 50.1.0
- Safari 10.0.1 (12602.2.14.0.7)
> Fix broken carousel

- spec/anchor.spec.js
- src/js/extensions/anchor.js
| Fixed tickets    | 1237
Fix for: https://github.com/yabwe/medium-editor/issues/1237
Previously URIs were split at a question mark to determine path and
query components. This caused a problem when fragments were part of a
link as they were deemed to be part of the query.
This splits a URL at a ? and a # to get both components and does not
encode the fragment. It did feel a little wrong not to encode the
fragment at all as there some characters that should be encoded, however
the encodeUriComponent method is too heavy handed for a fragment.
> Don't encode fragment as part of linkValidation

- README.md
- demo/custom-toolbar.html
- spec/buttons.spec.js
- src/js/core.js
- src/js/defaults/buttons.js
- src/js/extensions/README.md
| Fixed tickets    | (Finishing #1235)
A new tool button for evaluating inserted html, basically for embedding videos or objects.
Thanks to @vendelin8 for creating the feature!
> Adding new 'html' button from #1235

- README.md
- index.js
- package.json
Re-arranged README to:
* Bring basic screenshot above the fold
* Link to the actual demo via the screenshot
* Make the basic installation steps easier to find
* Update the image/link to saucelabs
* Add documentation for quickly running medium-editor demo
I've always had a basic static server file for running/developing/testing medium-editor locally, figured I should probably just check it in and save new people a little big of time when trying to run things locally.  I checked it in as `index.js` which can just be run via `node index.js` after doing an `npm install`.
> Update README + Add simple dev server for running locally

- spec/anchor.spec.js
- src/js/util.js
| Fixed tickets    | #1216 
From @annayafi in #1216:
> The problem was : when you call addClassToAnchors(el, buttonClass) function : 
> - if el is an `<a>` : no problem, it adds the css class(es)
> - if el has `<a>` children : no problem, it adds the css class(es) to children
> - if el is a child of an `<a>` : the function never looks for parent and won't add the css class(es). 
> This happens very easily when you select more than a node, for example you select exactly `<i>hello</i>`, css is never added.
This PR wraps up #1216 by fixing some spacing issues and resolving a bug in the code.  Thanks …
> Fix #1216 from previous PR #1217

- spec/anchor.spec.js
- src/js/extensions/anchor.js
| Fixed tickets    | 1250
Fixes: https://github.com/yabwe/medium-editor/issues/1250
This changes the way a scheme is prefixed to a URL when linkValidation
is on. Previously any URL that did not match the scheme regex would be
prefixed with 'http://' which meant that an absolute path such as '/'
would be changed to 'http:///'
This changes it so that the 'http://' is only prefixed if the first part
of the path looks like a hostname, which allows absolute paths to be
unchanged and most relative paths to be unchanged.
I say most as a path such as "test.txt" would be matched as a hostname and …
> Only add schemes to URLs with hostnames

- bower.json
| Fixed tickets    |  
In bower the directory ``src`` is ignored. That makes the sass part of medium not usable when loaded with bower.
> remove src from bower ignored files

- src/js/extensions/anchor.js
| Fixed tickets    | #1275 
Added id to anchor target checkbox using this.getEditorId() for
uniqueness, and then added the for attribute to the label
--
> Add label-checkbox relation in CreateLink form #1275

- dist/js/medium-editor.js
- spec/anchor.spec.js
- src/js/util.js
| BC breaks?       | yes
| Fixed tickets    | #1354
add `rel="noopener noreferrer"` into anchor, if targetBlank.
--
> add noopener & noreferrer into targetBlank

- src/js/extensions/paste.js
| Fixed tickets    | #1345
This fixes a use-case where `range.startContainer.getBoundingClientRect` is `undefined`, as described in #1345.
> Added undefined check and fallback in Paste extension

- src/js/core.js
| Fixed tickets    | #1369 
Firefox console warning when there are multiple medium editor textareas: "Use of attributes' nodeValue attribute is deprecated. Use value instead." This is coming from line 6929 in dist/js/medium-editor.js. By changing atts[i].nodeValue to atts[i].value the warning goes away as well as the bug this caused in the application where medium editor was being used (Firefox only).
> Bug fix for #1369

- src/js/events.js
In version 5.23.2 (and before, not sure from when) if you add a link with `data-disable-preview` it triggers an error when you `mouseout` it.
Here is a jsfiddle that repeat the issue. it pulls in medium-editor 5.23.2 from jscdn.
http://jsfiddle.net/92req5br/
> Do not check only for null targets or it will fail when it's undefined.

- src/js/events.js
`extensions` can under some circumstances be `undefined`. This causes an error when calling `extensions.some()` and for example stops `execAction` from having effect. Not sure if this is a good way to solve the issue, but it prevents the error.
> fix crash when 'extensions' in 'isElementDescendantOfExtension' is undefined

- spec/anchor-preview.spec.js
- spec/auto-link.spec.js
- spec/content.spec.js
- spec/toolbar.spec.js
Fix a bunch of unit tests that were failing upon running `npm run build`. Now everything builds fine again.
--
> Fix Jasmine Unit Test errors

- src/js/extensions/paste.js
| New tests added? | no
I saw some errors where pastedPlain was undefined, so the `.split` would throw an error.
I don't know if this is the best place to fix the bug, but I wanted to start a conversation around the bug nonetheless.
> fix null error on pastedPlain.split

- Gruntfile.js
- spec/buttons.spec.js
- spec/content.spec.js
See individual commit messages for details.
At a high level, I think these tests broke because the browsers decided to slightly change the markup they generate for `contenteditable` elements under various conditions.
This changeset finds a couple of places where this has been a problem and normalizes the output to what the tests expect. I don't think either of the normalizations that I'm performing is dangerous (i.e. potentially compromises the integrity of the tests and what they're meant to ensure), but please let me know if this is actually wrong.
> Fix broken browser tests

- src/js/extensions/anchor.js
| Fixed tickets    | -
Custom class option checkbox is not clickable due to missing `id` on checkbox and related `for` on label.
--
> Fixed custom class option checkbox

- spec/content.spec.js
- src/js/util.js
| Fixed tickets    | no
Currently in Chrome when removing ordered/unordered list you get a `<span>` element followed by a `<br>`  for every line instead of just `<p>` elements. Furthermore, when inserting a line break in the middle of a span like this, everything that goes after gets wrapped in a div, which is unwanted.
This fix simply goes through these spans and replaces them with proper `<p>` elements.
> Cleanup after ordered/unordered list removal in Chrome

- spec/content.spec.js
- src/js/util.js
| New tests added? | fixed old ones
| Fixed tickets    | none
Fixed my test cases for Edge, and fixed the cleanup in Firefox when selection start lays outside a text node.
All Saucelabs tests should pass now.
> Cleanup after ordered/unordered list item removal

- src/js/core.js
| New tests added? | no
| Fixed tickets    | #1496
For some reason in Firefox, the body is the focussed element after exec action. If there's a nicer way to do this (or to _stop_ the body being the focus) let me know and I'll be happy to investigate further.
> Ensure the focus stays in the editor after execAction for Firefox. #1496

- src/js/core.js
Also ensure that we select the parent is selected if ever a br tag is the selected element when typing. 
| New tests added? | no
| Fixed tickets    | #1455
I noticed in the `handleKeyup` method that sometimes the selected node was a BR tag. When this is the case, typing does nothing. The use case in the issue (which was a problem for me also) is when you press enter from a new heading - so I've added a fix for that scenario (wrapped in the isFF util). I also added a fallback check - since I've seen other random places where typing seems to get "trapped".
Very happy to work with you if you have suggestions for improvement …
> Ensure paragraph is selected for firefox. #1455
