README.md

- Re-organize the documented options
- Added the following to the documented options list:
+ staticToolbar
+ stickyToolbar
+ updateOnEmptySelection
+ disablePlaceholders
+ disableAnchorForm
+ onHideToolbar

Update README with recently added options

---

spec/init.spec.js
spec/selection.spec.js

- Fix two tests where the behavior between running in node vs the browser is inconsistent

Fix some tests that were broken in browsers

---

.gitignore
spec/init.spec.js
src/js/medium-editor.js
src/sass/medium-editor.scss

Image drag and drop support using HTML5 FileReader API, with custom styles when the editor is hovered and CSS animation when the image is loading. Tested on lastest Chrome and Firefox

Image drag&drop support

---

dist/js/medium-editor.js
src/js/core.js
src/js/util.js

Introduced a new control trying to fix the issue #430

Toolbar fix

---

dist/js/medium-editor.js
spec/buttons.spec.js
src/js/button.js
src/js/core.js

you can specify key for a button and on keydown with ctrl
it will trigger its action
fix #40

feat: implement keyboard shortcuts for commands

---

dist/js/medium-editor.js
src/js/core.js

this should work better for mac users
I hope it works, can't test this :smile: 
fix #40

fix(shortcuts): let metaKey trigger shortcuts

---

spec/anchor.spec.js

+ Added test for 'open in new window' checbkox
+ Added test for closing anchor form when user presses escape

99% coverage in extension-anchor.js

---

README.md

MediumButton update

---

LICENSE
README.md
bower.json
package.json

Closes #237
I know you're gonna miss the beer-ware license v. 42, but this is for the good of the project. 
:+1:

Uses MIT license

---

spec/activate.spec.js

As discussed in the [following PR](https://github.com/daviferreira/medium-editor/pull/452#issuecomment-76190664) :+1:

Re-enabled regression unit-test

---

Gruntfile.js
spec/activate.spec.js
spec/anchor-preview.spec.js
spec/anchor.spec.js
spec/buttons.spec.js
spec/content.spec.js
spec/helpers/util.js
spec/toolbar.spec.js

Change fireEvent parameters to options

Fire event

---

CHANGES.md

correct spelling in the CHANGES.md

CHANGES.md: s/initilization/initialization

---

dist/js/medium-editor.js
src/js/core.js
src/js/defaults/extensions.js
src/js/extensions/auto-link.js

Just polishing the work already done

Rename AutoLinker to AutoLink

---

src/js/core.js
src/js/defaults/options.js
src/js/events.js
src/js/extensions/anchor-preview.js
src/js/extensions/anchor.js
src/js/extensions/auto-link.js
src/js/extensions/button.js
src/js/extensions/fontsize.js
src/js/extensions/form.js
src/js/extensions/image-dragging.js
src/js/extensions/paste.js
src/js/extensions/placeholder.js
src/js/toolbar.js

One other cleanup before v5 :rocket: 
- avoid `else` condition when it's not necessary
- remove unnecessary empty line
- add some empty line for readability

Global cleanup

---

spec/toolbar.spec.js
src/js/core.js
src/js/toolbar.js

* and tests to ensure it works
* and test to ensure is fired before positionToolbar

implement updateToolbar

---

spec/buttons.spec.js
src/js/extensions/button.js

I want `ctrl+shift+I` to open devtools :P

Don't execute button shortcut when shift key is pressed

---

spec/anchor.spec.js
spec/buttons.spec.js
src/js/defaults/buttons.js
src/js/extensions/anchor.js

This PR fixes the issue with broken keyboard shortcuts in the pre-5.0.0 codebase.

Fix broken keyboard shortcuts :disappointed:

---

UPGRADE-5.md

Add an upgrade.md file to describe the steps on upgrading to version 5.0.0 of MediumEditor.

Add Upgrade-5.md

---

src/js/extensions/form.js

As required in #684, add showToolbarDefaultAction method in form extension module.

update: add showToolbarDefaultAction

---

bower.json

Why do people needs `sass` file in Bower ? (see #147)
ping @seifsallam @daviferreira @nchase

Ignore all source files

---

spec/setup.spec.js
src/js/core.js

Ensure all extra attributes are removed on destroy

---

spec/content.spec.js
src/js/core.js

I tried to solve https://github.com/yabwe/medium-editor/issues/595; I figured out the the problem in chrome was about `br`, tried to solve it saving the text before, replacing witouth `<br>`s and replacing it the formatting again with them. 
I was not able to make test.
Ask me anything if needed, thank you so much for this awesome repo :)

Justify behaviour

---

README.md
spec/helpers/util.js
spec/keyboard-commands.spec.js
src/js/extensions/keyboard-commands.js

Hello,
I added `alt` key option for keyboard commands
and the ability to toggle `h1` `h2` `h3` headers using shortcuts.
Thank you! :smiley: 
Dominic

keyboard commands alt key support

---

src/js/extensions/README.md

I created this extension to use myself. Hope it'd be useful for others too!

Add MediumEditorMultiPlaceholders extension to extension examples

---

README.md
demo/relative-toolbar.html
spec/toolbar.spec.js
src/js/extensions/toolbar.js
src/sass/components/_toolbar.scss

In relation to  this issue: https://github.com/yabwe/medium-editor/issues/499
I needed this feature for my current project, so i tried to make it kind of "official" would be happy if it makes it into master.
Not sure about specs, had no other ideas what to test, because all other features should be already covered.

Added toolbar-relative-container feature

---

spec/anchor.spec.js
src/js/core.js

fix anchor specs to select aTag when changing links

Fix changing links on images for firefox, #803

---

demo/auto-link.html
demo/index.html
demo/nested-editable.html

Fix font-awesome.css link in demo/auto-link.html

---

spec/content.spec.js
src/js/core.js

Fixed. https://github.com/yabwe/medium-editor/issues/831

disabled double enter issue on li tags

---

CUSTOM-EVENTS.md
OPTIONS.md
README.md
spec/content.spec.js
spec/init.spec.js
src/js/core.js
src/js/defaults/options.js
src/js/events.js

For this https://github.com/yabwe/medium-editor/issues/146

Optional space

---

Gruntfile.js
spec/fontname.spec.js
src/js/core.js
src/js/extensions/fontname.js

https://github.com/yabwe/medium-editor/issues/805
Based on the font size extension file, I've created a new font face extension. On line 94, the different font options are listed. How should this array be populated? Which font faces should be included?

Font Name Extension

---

spec/content.spec.js
src/js/core.js

For https://github.com/yabwe/medium-editor/issues/788

Return area

---

src/js/core.js

#886 - Cannot press space when i'm with the cursor at the end of line

---

src/sass/components/_placeholder.scss

Fixes https://github.com/yabwe/medium-editor/issues/895

Fix placeholder not paying attention to container padding and margins

---

src/js/util.js

When attempting to replace a `<blockquote>` with a `<p>` in firefox we were previously just calling `outdent` via `document.execCommand()`.
However, if the content within the `<blockquote>` is not contained within another block element (ie a `<p>`) we'll end up just stripping the `<blockquote>` and leaving text-nodes as direct children of the parent editor element (which we don't want).
This fix will ensure that before we 'outdent' a `<blockqoute>`, we make sure the content is wrapped in valid block elements and/or a `<p>`.

Fix execFormatBlock for firefox when converting a blockquote to a p

---

spec/content.spec.js

Add test for #887
Ping @patrinhani-ciandt

Add test for #887

---

OPTIONS.md
src/js/extensions/toolbar.js

I needed this option in order to keep on the screen a sticky toolbar when I have a static page header.

stickyTopOffset option added

---

spec/content.spec.js
src/js/core.js

handled enter event for empty h2/h3 tag 🔨

---

src/js/extensions/file-dragging.js

ImageDragging insert image at the end of dropping target

---

spec/content.spec.js
src/js/core.js

Fix for #982 . Changes includes a test case which reproduces the bug filed in #982 .

handle extra space when space already exists 🚧

---

OPTIONS.md
README.md

As promised in #970.
Feature was proposed (by @oste) and discussed in #534.
Its pull request (implementation from @j0k3r) was #627.

Documentation of placholder-option 'hideOnClick'

---

spec/auto-link.spec.js
src/js/extensions/auto-link.js

Fixed missing `editableInput` event on autolinking

---

spec/drag-and-drop.spec.js
src/js/extensions/file-dragging.js

Fix for #985

---

src/js/extensions/anchor.js

As discussed earlier - here the new branch, cleaned up, without anything touching in dest/ ;-) Containing only the fix for the anchor "show-form" logic

Fix anchor showform

---

spec/selection.spec.js
src/js/selection.js

PR for #983.
I saw that there's currently an open pull request (#984) to implement this functionality, but for core rather than selection.js, so I decided to write this and the appropriate unit-tests.

Adding clearSelection method to selection.js

---

src/sass/medium-editor.scss

Fix IE CSS bugs

---

API.md

Update API.md documentation to have argument summaries for all editor methods, including updates to options passed to `execAction()` and `createLink()`.

Update API.md with more details about arguments

---

OPTIONS.md
README.md

Documented the showOnEmptyLinks added in https://github.com/yabwe/medium-editor/pull/1100

documented the showOnEmptyLink option

---

package.json

- Grunt now it`s a local module, you don't need install it global.
- Added `npm run build` to run the grunt default task.
--

Changes at Package JSON

---

src/js/extensions/README.md

| Fixed tickets    | -
Added new extension repo url to extensions readme.md

Added Embed Button links to Readme.md

---

src/js/extensions/WALKTHROUGH-BUTTON.md

| Deprecations?    | yes
Rangy DEPRECATED warning
--
Rangy warning: DEPRECATED: createCssClassApplier  is deprecated. 
Use createClassApplier instead.

Update WALKTHROUGH docs

---

demo/button-example.html
src/js/extensions/WALKTHROUGH-BUTTON.md

WALKTHROUGH-BUTTON.md: Fix typo

---

src/js/extensions/anchor-preview.js

Following https://github.com/yabwe/medium-editor/pull/1203

Fix PR 1203

---

demo/button-example.html
demo/css/demo.css
demo/index.html

Hey guys,
I was just wondering where all demos are at your demo page? I see they are in the code but it's really uncomfortable to open each html file seperately. So I linked all demos from the index.html
Please merge. This is really important in my opinion.

Demo Page: Adding links to all other demos

---

spec/content.spec.js

| New tests added? | fixed old ones
| Fixed tickets    | none
This should fix Saucelabs test cases once and for all.

Remove IE check

---

src/js/extensions/form.js

| Fixed tickets    | comma-separated list of tickets fixed by the PR, if any
Modified description about a method.
--

Modify method name in comment

---

.travis.yml

| Fixed tickets    | none
Fix SouceLabes CI issue with regards to Node version (changed from v8 to v12).
--

Update pipeline Node version from 8 to 12.
